Repository cadet/CADET-Core, pull requests merged in 2024-11, with the labels that each got.

#316 Update README.rst
  README.rst
Labels: documentation

#315 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#311 Fix backwards compatibility of CSTR
  src/libcadet/model/StirredTankModel.cpp
Labels: bug

#310 Fix: Simulation with CSTR does not terminate
  src/libcadet/model/StirredTankModel.cpp
Labels: bug

#317 Add ZENODO metadata file
  .zenodo.json
  doc/developer_guide/release_new_version.rst
Labels: maintenance

#318 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#313 Improve PBM docs
  doc/interface/population_balance_model.rst
  doc/modelling/PBM_Part_I.png
  doc/modelling/crystallization.rst
Labels: documentation

#312 Update documentation
  LICENSE.txt
  README.rst
  doc/developer_guide/release_new_version.rst
Labels: documentation

#319 Update release guide
  doc/developer_guide/release_new_version.rst
Labels: documentation

#257 Add an exchange module for the MCT
  include/cadet/cadet.hpp
  src/libcadet/CMakeLists.txt
  src/libcadet/ConfigurationHelper.hpp
  src/libcadet/ExchangeModelFactory.cpp
  src/libcadet/ExchangeModelFactory.hpp
  src/libcadet/HighResKoren.hpp
  src/libcadet/ModelBuilderImpl.cpp
  src/libcadet/ModelBuilderImpl.hpp
  src/libcadet/model/ExchangeModel.hpp
  src/libcadet/model/ModelUtils.hpp
  src/libcadet/model/MultiChannelTransportModel.cpp
  src/libcadet/model/MultiChannelTransportModel.hpp
  src/libcadet/model/UnitOperationBase.cpp
  src/libcadet/model/UnitOperationBase.hpp
  src/libcadet/model/binding/LinearBinding.cpp
  src/libcadet/model/exchange/LinearExchange.cpp
  src/libcadet/model/parts/MultiChannelConvectionDispersionOperator.cpp
  src/libcadet/model/parts/MultiChannelConvectionDispersionOperator.hpp
  src/libcadet/model/reaction/CrystallizationReaction.cpp
  test/Crystallization.cpp
  test/Dummies.hpp
Labels: feature request, unit operation model
