Repository cadet/CADET-Core, pull requests merged in 2024-12, with the labels that each got.

#335 Resolve interface inconsistencies between CLI-interface and C-API
  include/common/SolutionRecorderImpl.hpp
  src/libcadet/model/StirredTankModel.hpp
Labels: bug, interface

#342 Add exception for non-parallelized code when NTHREADS > 1
  src/libcadet/SimulatorImpl.cpp
  test/ColumnTests.cpp
  test/data/configuration_PBM_CSTR_growthSizeDep_benchmark1.json
  test/data/configuration_PBM_CSTR_growth_benchmark1.json
  test/data/configuration_PBM_CSTR_primaryNucleationAndGrowth_benchmark1.json
  test/data/configuration_PBM_CSTR_primaryNucleationGrowthGrowthRateDispersion_benchmark1.json
  test/data/configuration_PBM_CSTR_primarySecondaryNucleationAndGrowth_benchmark1.json
Labels: maintenance

#343 Update issue templates
  .github/ISSUE_TEMPLATE/release_checklist.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, maintenance

#346 Bump version to v5.0.3
  .zenodo.json
  doc/cadet.doxyfile
  include/cadet/cadet.hpp
  include/common/Driver.hpp
  version.txt
Labels: maintenance

#341 Update conda link in README.rst
  README.rst
  doc/getting_started/installation.rst
Labels: documentation

#349 Fix manual trigger of CI and CD workflows
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: test

#347 Update release checklist
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: maintenance
