Repository cadet/CADET-Core, pull requests merged in 2024-06, with the labels that each got.

#207 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#180 Simple Michaelis-Menten reaction kinetics
  src/libcadet/CMakeLists.txt
  src/libcadet/ReactionModelFactory.cpp
  src/libcadet/model/Parameters.hpp
  src/libcadet/model/reaction/MichaelisMentenReaction.cpp
  test/ColumnTests.cpp
  test/ColumnTests.hpp
  test/ReactionModelTests.cpp
  test/ReactionModelTests.hpp
  test/ReactionModels.cpp
  test/data/configuration_CSTR_MichaelisMenten_benchmark1.json
  test/data/configuration_CSTR_MichaelisMenten_benchmark2.json
  test/data/configuration_CSTR_MicroKineticsSMA_benchmark1.json
  test/data/ref_CSTR_MichaelisMenten_benchmark2.h5
Labels: reaction model

#222 Add CLA and CLA workflow
  .github/workflows/cla.yml
  CLA.md
Labels: maintenance
