Repository cadet/CADET-Core, pull requests merged in 2024-08, with the labels that each got.

#261 Add linearization to Mobile Phase Modulator Langmuir Binding
  src/libcadet/model/binding/MobilePhaseModulatorLangmuirBinding.cpp
  test/BindingModels.cpp
Labels: enhancement, binding model, maintenance

#264 Fix narrowing conversion in LRMP_DG for CADET_PARALLELIZE code block
  src/libcadet/model/GeneralRateModelDG-InitialConditions.cpp
  src/libcadet/model/LumpedRateModelWithPoresDG-InitialConditions.cpp
Labels: maintenance

#267 Fix optional build of DG units
  src/libcadet/AdUtils.cpp
  src/libcadet/AdUtils.hpp
  src/libcadet/AutoDiff.hpp
  src/libcadet/linalg/Subset.hpp
  src/libcadet/model/GeneralRateModelBuilder.cpp
  src/libcadet/model/LumpedRateModelWithPoresBuilder.cpp
  src/libcadet/model/LumpedRateModelWithoutPoresBuilder.cpp
  src/libcadet/model/ReactionModel.hpp
  src/libcadet/model/binding/DummyBinding.cpp
  src/libcadet/model/binding/LinearBinding.cpp
  test/CMakeLists.txt
Labels: maintenance

#187 Add `CSTR` to `createLWE`
  src/tools/createLWE.cpp
Labels: dev-call

#269 Improve compilation speed on MS Windows
  .gitignore
  CMakeLists.txt
  CMakeSettings.json
Labels: maintenance

#274 Add option to specify cross section area for 2D-GRM
  doc/interface/unit_operations/2d_general_rate_model.rst
  src/libcadet/model/parts/TwoDimensionalConvectionDispersionOperator.cpp
Labels: interface

#263 Expand developer guide
  doc/developer_guide/TemplateBinding.cpp
  doc/developer_guide/architecture_libcadet_classes.png
  doc/developer_guide/build_options.rst
  doc/developer_guide/cadet_core_architecture.rst
  doc/developer_guide/debugging.rst
  doc/developer_guide/index.rst
  doc/developer_guide/model_expansion.rst
  doc/developer_guide/testing.rst
  doc/getting_started/build_linux.rst
  doc/getting_started/build_osx.rst
  doc/getting_started/build_windows.rst
Labels: documentation

#281 Fix invalid CMake install option in MacOS CI
  .github/workflows/ci.yml
Labels: maintenance
