Repository cadet/CADET-Core, pull requests merged in 2024-07, with the labels that each got.

#220 Automatically compute binding model Jacobians via AD
  src/libcadet/AdUtils.cpp
  src/libcadet/AdUtils.hpp
  src/libcadet/BindingModelFactory.cpp
  src/libcadet/model/BindingModel.hpp
  src/libcadet/model/GeneralRateModel.cpp
  src/libcadet/model/GeneralRateModel2D.cpp
  src/libcadet/model/GeneralRateModelDG.cpp
  src/libcadet/model/LumpedRateModelWithPores.cpp
  src/libcadet/model/LumpedRateModelWithPoresDG.cpp
  src/libcadet/model/LumpedRateModelWithoutPores.cpp
  src/libcadet/model/LumpedRateModelWithoutPoresDG.cpp
  src/libcadet/model/StirredTankModel.cpp
  src/libcadet/model/UnitOperationBase.cpp
  src/libcadet/model/UnitOperationBase.hpp
  src/libcadet/model/binding/AntiLangmuirBinding.cpp
  src/libcadet/model/binding/BiLangmuirBinding.cpp
  src/libcadet/model/binding/BiLangmuirLDFBinding.cpp
  src/libcadet/model/binding/BiStericMassActionBinding.cpp
  src/libcadet/model/binding/BindingModelBase.hpp
  src/libcadet/model/binding/ColloidalBinding.cpp
  src/libcadet/model/binding/DummyBinding.cpp
  src/libcadet/model/binding/ExtendedMobilePhaseModulatorLangmuirBinding.cpp
  src/libcadet/model/binding/FreundlichLDFBinding.cpp
  src/libcadet/model/binding/GeneralizedIonExchangeBinding.cpp
  src/libcadet/model/binding/HICConstantWaterActivityBinding.cpp
  src/libcadet/model/binding/HICWaterOnHydrophobicSurfacesBinding.cpp
  src/libcadet/model/binding/KumarLangmuirBinding.cpp
  src/libcadet/model/binding/LangmuirBinding.cpp
  src/libcadet/model/binding/LangmuirLDFBinding.cpp
  src/libcadet/model/binding/LangmuirLDFCBinding.cpp
  src/libcadet/model/binding/LinearBinding.cpp
  src/libcadet/model/binding/MobilePhaseModulatorLangmuirBinding.cpp
  src/libcadet/model/binding/MultiComponentSpreadingBinding.cpp
  src/libcadet/model/binding/MultiStateStericMassActionBinding.cpp
  src/libcadet/model/binding/SaskaBinding.cpp
  src/libcadet/model/binding/SelfAssociationBinding.cpp
  src/libcadet/model/binding/SimplifiedMultiStateStericMassActionBinding.hpp
  src/libcadet/model/binding/StericMassActionBinding.cpp
  test/BindingModelAutoJacobian.cpp
  test/CMakeLists.txt
  test/Dummies.hpp
  test/JsonTestModels.hpp
Labels: enhancement, binding model, numerics

#212 Enable choice of different linear solvers in DG units
  src/libcadet/CMakeLists.txt
  src/libcadet/linalg/EigenSolverWrapper.cpp
  src/libcadet/linalg/EigenSolverWrapper.hpp
  src/libcadet/model/GeneralRateModelDG-InitialConditions.cpp
  src/libcadet/model/GeneralRateModelDG-LinearSolver.cpp
  src/libcadet/model/GeneralRateModelDG.cpp
  src/libcadet/model/GeneralRateModelDG.hpp
  src/libcadet/model/LumpedRateModelWithPoresDG-InitialConditions.cpp
  src/libcadet/model/LumpedRateModelWithPoresDG-LinearSolver.cpp
  src/libcadet/model/LumpedRateModelWithPoresDG.cpp
  src/libcadet/model/LumpedRateModelWithPoresDG.hpp
  src/libcadet/model/LumpedRateModelWithoutPoresDG.cpp
  src/libcadet/model/LumpedRateModelWithoutPoresDG.hpp
Labels: enhancement, numerics

#208 Temporarily add the developer_guide branch to sphinx multiversion
  doc/conf.py
Labels: documentation

#181 Add developer guide documentation
  doc/developer_guide/debugging.rst
  doc/developer_guide/index.rst
  doc/developer_guide/launch.vs.json
  doc/developer_guide/model_expansion.rst
  doc/developer_guide/testing.rst
  doc/index.rst
Labels: documentation

#219 Disable IPO by default on debug builds in CMake
  CMakeLists.txt
Labels: enhancement

#209 Add build configurations for testing
  CMakeSettings.json
Labels: enhancement

#204 Update to cpp23 standard
  CMakeLists.txt
  ThirdParty/tclap/include/tclap/ArgTraits.h
  ThirdParty/tclap/include/tclap/MultiArg.h
  ThirdParty/tclap/include/tclap/ValueArg.h
  src/build-tools/CMakeLists.txt
Labels: enhancement
