Repository cadet/CADET-Core, pull requests merged in 2024-10, with the labels that each got.

#289 Add MCT exchange matrix sensitivity to documentation
  doc/interface/unit_operations/multi_channel_transport_model.rst
  include/cadet/ParameterId.hpp
Labels: documentation

#300 Change links to new repository address
  .github/workflows/cla.yml
  BUILD-LINUX.md
  BUILD-OSX.md
  BUILD-WINDOWS.md
  CLA.md
  CMakeLists.txt
  README.rst
  doc/developer_guide/index.rst
  doc/index.rst
Labels: documentation, maintenance

#305 Update developer guide links to CADET-Verification
  doc/developer_guide/testing.rst
Labels: documentation

#282 Add release guide to documentation
  doc/developer_guide/index.rst
  doc/developer_guide/release_new_version.rst
Labels: documentation

#276 v5.0.0
  doc/cadet.doxyfile
  include/cadet/cadet.hpp
  version.txt
Labels: maintenance
