Repository cadet/CADET-Core, pull requests merged in 2025-03, with the labels that each got.

#375 Fix PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: maintenance

#369 LICENSE: use https instead of http
  LICENSE.txt
Labels: maintenance

#361 Update AUTHORS.md
  AUTHORS.md
Labels: maintenance

#370 SelectiveStdWritePolicy::writeObj: write logs
  include/common/Logger.hpp
Labels: bug

#378 CADET-Python example: fix bugs, clarify cadet_path
  doc/developer_guide/examples/breakthrough.py
Labels: documentation
